/*!
**  Ducky -- Duck-Typed Value Handling for JavaScript
**  Copyright (c) 2010-2015 Ralf S. Engelschall <rse@engelschall.com>
**
**  Permission is hereby granted, free of charge, to any person obtaining
**  a copy of this software and associated documentation files (the
**  "Software"), to deal in the Software without restriction, including
**  without limitation the rights to use, copy, modify, merge, publish,
**  distribute, sublicense, and/or sell copies of the Software, and to
**  permit persons to whom the Software is furnished to do so, subject to
**  the following conditions:
**
**  The above copyright notice and this permission notice shall be included
**  in all copies or substantial portions of the Software.
**
**  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
**  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
**  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
**  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
**  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
**  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
**  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.Ducky = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var version={major:2,minor:1,micro:3,date:20150125};exports.version=version;
},{}],2:[function(_dereq_,module,exports){
"use strict";function _classCallCheck(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(exports,"__esModule",{value:!0});var _createClass=function(){function e(e,t){for(var s=0;s<t.length;s++){var n=t[s];n.enumerable=n.enumerable||!1,n.configurable=!0,"value"in n&&(n.writable=!0),Object.defineProperty(e,n.key,n)}}return function(t,s,n){return s&&e(t.prototype,s),n&&e(t,n),t}}(),Token=function(){function e(){_classCallCheck(this,e),this.name="",this.text="",this.tokens=[],this.pos=0,this.len=0}return _createClass(e,[{key:"setName",value:function(e){this.name=e}},{key:"setText",value:function(e){this.text=e}},{key:"addToken",value:function(e,t,s,n,o){this.tokens.push({b1:e,b2:t,e2:s,e1:n,symbol:o}),this.len++}},{key:"peek",value:function(e){if("undefined"==typeof e&&(e=0),e>=this.len)throw new Error(this.name+": parse error: not enough tokens");return this.tokens[this.pos+e].symbol}},{key:"skip",value:function(e){if("undefined"==typeof e&&(e=1),e>this.len)throw new Error(this.name+": parse error: not enough tokens available to skip: "+this.ctx());this.pos+=e,this.len-=e}},{key:"consume",value:function(e){if(this.len<=0)throw new Error(this.name+": parse error: no more tokens available to consume: "+this.ctx());if(this.tokens[this.pos].symbol!==e)throw new Error(this.name+': parse error: expected token symbol "'+e+'": '+this.ctx());this.pos++,this.len--}},{key:"ctx",value:function t(e){"undefined"==typeof e&&(e=78);var s=this.tokens[this.pos],t="<"+this.text.substr(s.b2,s.e2-s.b2+1)+">";t=this.text.substr(s.b1,s.b2-s.b1)+t,t+=this.text.substr(s.e2+1,s.e1-s.e2);var n=e-t.length;if(n>0){n=Math.floor(n/2);var o=void 0,i=void 0;if(this.pos>0){var r=0;for(o=this.pos-1;o>=0&&(s=this.tokens[o],i=this.text.substr(s.b1,s.e1-s.b1+1),r+=i.length,!(r>n));o--)t=i+t;o>0&&(t="[...]"+t)}if(this.len>1){var h=0;for(o=this.pos+1;o<this.pos+this.len&&(s=this.tokens[o],i=this.text.substr(s.b1,s.e1-s.b1+1),h+=i.length,!(h>n));o++)t+=i;o<this.pos+this.len&&(t+="[...]")}}return t=t.replace(/\r/,"\\r").replace(/\n/,"\\n").replace(/\t/,"\\t")}}]),e}();exports.Token=Token;
},{}],3:[function(_dereq_,module,exports){
(function (global){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});for(var registry={},std_types=["Object","Boolean","Number","String","Function","RegExp","Array","Date","Error","Set","Map","WeakMap","Promise","Proxy","Iterator"],i=0;i<std_types.length;i++)"function"==typeof global[std_types[i]]&&(registry[std_types[i]]=global[std_types[i]]);exports.registry=registry;
}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})

},{}],4:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _ducky2Registry1DataJs=_dereq_("./ducky-2-registry-1-data.js"),register=function(e,r){if(2!==arguments.length)throw new Error("register: invalid number of arguments: "+arguments.length+" (exactly 2 expected)");if("string"!=typeof e)throw new Error('register: invalid name argument: "'+e+'" (string expected)');if("function"!=typeof r)throw new Error('register: invalid type argument: "'+r+'" (function object expected)');if("undefined"!=typeof _ducky2Registry1DataJs.registry[e])throw new Error('register: type already registered under name: "'+e+'"');_ducky2Registry1DataJs.registry[e]=r},unregister=function(e){if(1!==arguments.length)throw new Error("unregister: invalid number of arguments: "+arguments.length+" (exactly 1 expected)");if("string"!=typeof e)throw new Error('unregister: invalid name argument: "'+e+'" (string expected)');if("undefined"==typeof _ducky2Registry1DataJs.registry[e])throw new Error('unregister: no type registered under name: "'+e+'"');delete _ducky2Registry1DataJs.registry[e]},registered=function(e){if(1!==arguments.length)throw new Error("registered: invalid number of arguments: "+arguments.length+" (exactly 1 expected)");if("string"!=typeof e)throw new Error('registered: invalid name argument: "'+e+'" (string expected)');return _ducky2Registry1DataJs.registry[e]};exports.registered=registered,exports.register=register,exports.unregister=unregister;
},{"./ducky-2-registry-1-data.js":3}],5:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var select_compile=function(e){for(var s=[],l=0,r=void 0,t=e;""!==t;){if(null!==(r=t.match(/^\s*(?:\.)?\s*([a-zA-Z$0-9_][a-zA-Z$0-9_:-]*)/)))s.push(r[1]);else if(null!==(r=t.match(/^\s*\[\s*(\d+|\*{1,2})\s*\]/)))s.push(r[1]);else if(null!==(r=t.match(/^\s*\[\s*"((?:\\"|.)*?)"\s*\]/)))s.push(r[1].replace(/\\"/g,'"'));else{if(null===(r=t.match(/^\s*\[\s*'((?:\\'|.)*?)'\s*\]/))){if(null!==(r=t.match(/^\s+$/)))break;throw new Error("select: parse error: invalid character at: "+e.substr(0,l)+"<"+t.substr(0,1)+">"+t.substr(1))}s.push(r[1].replace(/\\'/g,"'"))}l+=r[0].length,t=t.substr(r[0].length)}return s};exports.select_compile=select_compile;
},{}],6:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var select_execute=function(e,t){if(0===t.length){if(3===arguments.length)throw new Error("select: cannot set value on empty path");return e}for(var r=0;r<t.length-1;){if("object"!=typeof e)throw new Error("select: cannot further dereference: no more intermediate objects in path");e=e[t[r++]]}if("object"!=typeof e)throw new Error("select: cannot further dereference: no object at end of path");var n=e[t[r]];if(3===arguments.length){var o=arguments[2];void 0===o?e instanceof Array?e.splice(parseInt(t[r],10),1):delete e[t[r]]:e[t[r]]=o}return n};exports.select_execute=select_execute;
},{}],7:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _ducky3Select1CompileJs=_dereq_("./ducky-3-select-1-compile.js"),_ducky3Select2ExecuteJs=_dereq_("./ducky-3-select-2-execute.js"),select_cache={},select=function(e,t,r){if(arguments.length<2)throw new Error("select: invalid number of arguments: "+arguments.length+" (minimum of 2 expected)");if(arguments.length>3)throw new Error("select: invalid number of arguments: "+arguments.length+" (maximum of 3 expected)");if("string"!=typeof t)throw new Error('select: invalid specification argument: "'+t+'" (string expected)');var c=select_cache[t];return"undefined"==typeof c&&(c=_ducky3Select1CompileJs.select_compile(t),select_cache[t]=c),2===arguments.length?_ducky3Select2ExecuteJs.select_execute(e,c):_ducky3Select2ExecuteJs.select_execute(e,c,r)};select.compile=function(e){if(1!==arguments.length)throw new Error("select: invalid number of arguments: "+arguments.length+" (exactly 1 expected)");if("string"!=typeof e)throw new Error('select: invalid specification argument: "'+e+'" (string expected)');return _ducky3Select1CompileJs.select_compile.apply(void 0,arguments)},select.execute=function(e,t){if(arguments.length<2)throw new Error("select: invalid number of arguments: "+arguments.length+" (minimum of 2 expected)");if(arguments.length>3)throw new Error("select: invalid number of arguments: "+arguments.length+" (maximum of 3 expected)");if(!("object"==typeof t&&t instanceof Array))throw new Error('select: invalid path argument: "'+t+'" (array expected)');return _ducky3Select2ExecuteJs.select_execute.apply(void 0,arguments)},exports.select=select;
},{"./ducky-3-select-1-compile.js":5,"./ducky-3-select-2-execute.js":6}],8:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _ducky1UtilJs=_dereq_("./ducky-1-util.js"),validate_tokenize=function(e){var t=new _ducky1UtilJs.Token;t.setName("validate"),t.setText(e);for(var r=void 0,n=0;""!==e;){if(r=e.match(/^(\s*)([^{}\[\]:,?*+()!|\s]+|[{}\[\]:,?*+()!|])(\s*)/),null===r)throw new Error('validate: parse error: cannot further canonicalize: "'+e+'"');t.addToken(n,n+r[1].length,n+r[1].length+r[2].length-1,n+r[0].length-1,r[2]),e=e.substr(r[0].length),n+=r[0].length}return t};exports.validate_tokenize=validate_tokenize;
},{"./ducky-1-util.js":2}],9:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var validate_parse={parse_spec:function(e){if(e.len<=0)return null;var r=void 0,a=e.peek();if("!"===a)r=this.parse_not(e);else if("("===a)r=this.parse_group(e);else if("{"===a)r=this.parse_hash(e);else if("["===a)r=this.parse_array(e);else if(a.match(/^(?:null|undefined|boolean|number|string|function|object)$/))r=this.parse_primary(e);else if("any"===a)r=this.parse_any(e);else{if(!a.match(/^[_a-zA-Z$][_a-zA-Z$0-9]*(?:\.[_a-zA-Z$][_a-zA-Z$0-9]*)*$/))throw new Error('validate: parse error: invalid token symbol: "'+e.ctx()+'"');r=this.parse_class(e)}return r},parse_not:function(e){e.consume("!");var r=this.parse_spec(e);return r={type:"not",op:r}},parse_group:function(e){e.consume("(");for(var r=this.parse_spec(e);"|"===e.peek();){e.consume("|");var a=this.parse_spec(e);r={type:"or",op1:r,op2:a}}return e.consume(")"),r},parse_hash:function(e){e.consume("{");for(var r=[];"}"!==e.peek();){var a=this.parse_key(e),s=this.parse_arity(e,"?");e.consume(":");var t=this.parse_spec(e);if(r.push({type:"element",key:a,arity:s,element:t}),","!==e.peek())break;e.skip()}var p={type:"hash",elements:r};return e.consume("}"),p},parse_array:function(e){e.consume("[");for(var r=[];"]"!==e.peek();){var a=this.parse_spec(e),s=this.parse_arity(e,"?*+");if(r.push({type:"element",element:a,arity:s}),","!==e.peek())break;e.skip()}var t={type:"array",elements:r};return e.consume("]"),t},parse_primary:function(e){var r=e.peek();if(!r.match(/^(?:null|undefined|boolean|number|string|function|object)$/))throw new Error('validate: parse error: invalid primary type "'+r+'"');return e.skip(),{type:"primary",name:r}},parse_any:function(e){var r=e.peek();if("any"!==r)throw new Error('validate: parse error: invalid any type "'+r+'"');return e.skip(),{type:"any"}},parse_class:function(e){var r=e.peek();if(!r.match(/^[_a-zA-Z$][_a-zA-Z$0-9]*(?:\.[_a-zA-Z$][_a-zA-Z$0-9]*)*$/))throw new Error('validate: parse error: invalid class type "'+r+'"');return e.skip(),{type:"class",name:r}},parse_arity:function(e,r){var a=[1,1];if(e.len>=5&&"{"===e.peek(0)&&e.peek(1).match(/^[0-9]+$/)&&","===e.peek(2)&&e.peek(3).match(/^(?:[0-9]+|oo)$/)&&"}"===e.peek(4))a=[parseInt(e.peek(1),10),"oo"===e.peek(3)?Number.MAX_VALUE:parseInt(e.peek(3),10)],e.skip(5);else if(e.len>=1&&1===e.peek().length&&r.indexOf(e.peek())>=0){var s=e.peek();switch(s){case"?":a=[0,1];break;case"*":a=[0,Number.MAX_VALUE];break;case"+":a=[1,Number.MAX_VALUE]}e.skip()}return a},parse_key:function(e){var r=e.peek();if(!r.match(/^(?:[_a-zA-Z$][_a-zA-Z$0-9]*|@)$/))throw new Error('validate: parse error: invalid key "'+r+'"');return e.skip(),r}};exports.validate_parse=validate_parse;
},{}],10:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _ducky2Registry2ApiJs=_dereq_("./ducky-2-registry-2-api.js"),validate_execute={exec_spec:function(e,t){var r=!1;if(null!==t)switch(t.type){case"not":r=this.exec_not(e,t);break;case"or":r=this.exec_or(e,t);break;case"hash":r=this.exec_hash(e,t);break;case"array":r=this.exec_array(e,t);break;case"primary":r=this.exec_primary(e,t);break;case"class":r=this.exec_class(e,t);break;case"any":r=!0;break;default:throw new Error('validate: invalid validation AST: node has unknown type "'+t.type+'"')}return r},exec_not:function(e,t){return!this.exec_spec(e,t.op)},exec_or:function(e,t){return this.exec_spec(e,t.op1)||this.exec_spec(e,t.op2)},exec_hash:function(e,t){var r=void 0,a=void 0,c="object"==typeof e,n={},i=void 0;if(c){var o=!1;for(i in e)if(Object.hasOwnProperty.call(e,i)&&Object.propertyIsEnumerable.call(e,i)&&"constructor"!==i&&"prototype"!==i){o=!0;break}for(r=0;r<t.elements.length;r++)if(a=t.elements[r],n[a.key]=a.element,a.arity[0]>0&&("@"===a.key&&!o||"@"!==a.key&&"undefined"==typeof e[a.key])){c=!1;break}}if(c)for(i in e)if(Object.hasOwnProperty.call(e,i)&&Object.propertyIsEnumerable.call(e,i)&&"constructor"!==i&&"prototype"!==i&&!("undefined"!=typeof n[i]&&this.exec_spec(e[i],n[i])||"undefined"!=typeof n["@"]&&this.exec_spec(e[i],n["@"]))){c=!1;break}return c},exec_array:function(e,t){var r=void 0,a=void 0,c="object"==typeof e&&e instanceof Array;if(c){var n=0;for(r=0;r<t.elements.length;r++){a=t.elements[r];for(var i=0;i<a.arity[1]&&n<e.length&&this.exec_spec(e[n],a.element);)i++,n++;if(i<a.arity[0]){c=!1;break}}n<e.length&&(c=!1)}return c},exec_primary:function(e,t){return"null"===t.name&&null===e||typeof e===t.name},exec_class:function(e,t){var r=_ducky2Registry2ApiJs.registered(t.name);return"object"==typeof e&&(Object.prototype.toString.call(e)==="[object "+t.name+"]"||"function"==typeof r&&e instanceof r)}};exports.validate_execute=validate_execute;
},{"./ducky-2-registry-2-api.js":4}],11:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _ducky4Validate1TokenizeJs=_dereq_("./ducky-4-validate-1-tokenize.js"),_ducky4Validate2ParseJs=_dereq_("./ducky-4-validate-2-parse.js"),_ducky4Validate3ExecuteJs=_dereq_("./ducky-4-validate-3-execute.js"),validate_cache={},validate=function e(t,a){if(2!==arguments.length)throw new Error("validate: invalid number of arguments: "+arguments.length+" (exactly 2 expected)");if("string"!=typeof a)throw new Error('validate: invalid specification argument: "'+a+'" (string expected)');var i=validate_cache[a];return"undefined"==typeof i&&(i=e.compile(a),validate_cache[a]=i),e.execute(t,i)};validate.compile=function(e){if(1!==arguments.length)throw new Error("validate: invalid number of arguments: "+arguments.length+" (exactly 1 expected)");if("string"!=typeof e)throw new Error('validate: invalid specification argument: "'+e+'" (string expected)');var t=_ducky4Validate1TokenizeJs.validate_tokenize(e),a=_ducky4Validate2ParseJs.validate_parse.parse_spec(t);return a},validate.execute=function(e,t){if(2!==arguments.length)throw new Error("validate: invalid number of arguments: "+arguments.length+" (exactly 2 expected)");return _ducky4Validate3ExecuteJs.validate_execute.exec_spec(e,t)},exports.validate=validate;
},{"./ducky-4-validate-1-tokenize.js":8,"./ducky-4-validate-2-parse.js":9,"./ducky-4-validate-3-execute.js":10}],12:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _ducky4Validate4ApiJs=_dereq_("./ducky-4-validate-4-api.js"),params_is_name_based=function(e,r){var a=!1;if(1===e.length&&"object"==typeof e[0]){a=!0;for(var i in e[0])Object.hasOwnProperty.call(e[0],i)||"undefined"==typeof r[i]&&(a=!1)}return a},params_check_validity=function(e,r,a,i,t){if("undefined"!=typeof i&&!_ducky4Validate4ApiJs.validate(a,i))throw new Error(e+': parameter "'+r+'" has '+(t+" "+JSON.stringify(a)+', which does not validate against "'+i+'"'))},params=function e(r,a,i){var e={},t=void 0;for(t in i)Object.hasOwnProperty.call(i,t)&&"undefined"!=typeof i[t].def&&("undefined"!=typeof i[t].valid&&params_check_validity(r,t,i[t].def,i[t].valid,"default value"),e[t]=i[t].def);if(params_is_name_based(a,i)){a=a[0];for(t in a)if(Object.hasOwnProperty.call(a,t)){if("undefined"==typeof i[t])throw new Error(r+': unknown parameter "'+t+'"');params_check_validity(r,t,a[t],i[t].valid,"value"),e[t]=a[t]}for(t in i)if(Object.hasOwnProperty.call(i,t)&&"undefined"!=typeof i[t].req&&i[t].req&&"undefined"==typeof a[t])throw new Error(r+': required parameter "'+t+'" missing')}else{var n=0,d=0,o={};for(t in i)Object.hasOwnProperty.call(i,t)&&"undefined"!=typeof i[t].pos&&(o[i[t].pos]=t,"number"==typeof i[t].pos&&n++,"undefined"!=typeof i[t].req&&i[t].req&&d++);if(a.length<d)throw new Error(r+": invalid number of arguments (at least "+d+" required)");for(var f=0;n>f&&f<a.length;)params_check_validity(r,o[f],a[f],i[o[f]].valid,"value"),e[o[f]]=a[f],f++;if(f<a.length){if("undefined"==typeof o["..."])throw new Error(r+": too many arguments provided");for(var p=[];f<a.length;)p.push(a[f++]);params_check_validity(r,o["..."],p,i[o["..."]].valid,"value"),e[o["..."]]=p}}return e};exports.params=params;
},{"./ducky-4-validate-4-api.js":11}],13:[function(_dereq_,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _ducky0VersionJs=_dereq_("./ducky-0-version.js"),_ducky2Registry2ApiJs=_dereq_("./ducky-2-registry-2-api.js"),_ducky3Select3ApiJs=_dereq_("./ducky-3-select-3-api.js"),_ducky4Validate4ApiJs=_dereq_("./ducky-4-validate-4-api.js"),_ducky5ParamsJs=_dereq_("./ducky-5-params.js");exports.version=_ducky0VersionJs.version,exports.register=_ducky2Registry2ApiJs.register,exports.unregister=_ducky2Registry2ApiJs.unregister,exports.select=_ducky3Select3ApiJs.select,exports.validate=_ducky4Validate4ApiJs.validate,exports.params=_ducky5ParamsJs.params;
},{"./ducky-0-version.js":1,"./ducky-2-registry-2-api.js":4,"./ducky-3-select-3-api.js":7,"./ducky-4-validate-4-api.js":11,"./ducky-5-params.js":12}]},{},[13])(13)
});


//# sourceMappingURL=ducky.browser.map